# Generated by Django 3.2.2 on 2021-05-13 08:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_groupassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupassignment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groupassignment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
